app:
  debug: false
  storageRootDirectoryName: "drophere"
  templatePath: "files/template"
  passwordRecovery:
    tokenExpiryDuration: 5 # in minutes
    webURL: "http://localhost:3000/reset-password"
    mailer:
      email: "bot@comeapp.id"
      name: "Drophere Bot"

db:
  dsn: "user:pwd@tcp(localhost:3306)/drophere?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true"

jwt:
  secret: "please-put-your-secret-key-here"
  duration: 8760 # in hours (token duration)
  signingAlgorithm: HS256

mailer:
  mailtrap:
    host: "smtp.mailtrap.io"
    port: 587
    username: ""
    password: 
    encryption: "tls"
  sendgrid:
    apiKey: ""
