version: "3"
services:
  app:
    container_name: ${APP_CONTAINER}
    build: .
    env_file: 
        - .env
    ports:
      - "${APP_PORT}:8080"
    restart: on-failure
    volumes:
      - ./backup_app:/usr/src/app/
    depends_on:
      - mysql-db
    networks:
      - drophere_networks

  mysql-db:
    image: mysql:5.7
    container_name: ${DB_HOST}
    restart: on-failure
    env_file: 
        - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - drophere_networks

volumes:
  api:
  database_mysql:

networks:
  drophere_networks:
    driver: bridge
